### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by schonhose** [mkucej/i-librarian-free#29] opened 2020-05-28 19:27 UTC
I get the following error when trying to login at 5.2.3 (although I still have previous issues):

```
500 Internal Server Error
E_WARNING: Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I' (this will throw an Error in a future version of PHP).
```
Error log from apache is empty.

**Comment by mkucej** [comment] 2020-06-02 21:07
duplicate of #26

**Closed by mkucej** 2020-06-02 21:07 UTC
Labels: duplicate
